### ISSUE TITLE
Background Image

### ISSUE THREAD

**Issue by kallyas** [ampaire/weather-app#6]
I have a suggestion, It could be nice when you have a background based on the weather condition. For example, If it is sunny, then a kind of sunny weather background should appear.

Thank you for the great work

**Comment by ampaire** [comment]
@kallyas, thanks for the suggestion. I will surely look into how to retain the city's image while also displaying the weather image. Thanks so much

**Comment by kallyas** [comment]
@ampaire   You're welcome.  Ternary if condition can solve this quickly
